### ISSUE TITLE
GTM event vimeoTrack is fired twice

### ISSUE THREAD

**Issue by mmadmar** [lunametrics/vimeo-google-analytics#1]
Hi all,

I am using the vimeo tracking tag in GTM and I am experiencing the following issue.
When testing the tag in GTM using debug mode I see that the vimeo event "vimeoTrack" is always fired  twice when I do any interaction with the videos.
Also the corresponding GA events appear twice in the browser console.

Does anyone experience the same?

Thanks
Mmadmar

**Comment by DanWilkerson** [comment]
Sounds like you've got either two containers on the page or the same container twice and both are firing the listener. If you share an example URL I can take a quick check.

**Comment by mmadmar** [comment]
Hi Dan,

please look at the video on the following page:

https://www.reddy.de/service/kuechen-service-von-reddy/

For the "Pause" event I am seeing the following two collects in the browser console:

v:1
_v:j63
a:1663437289
t:event
ni:0
_s:1
dl:https://www.reddy.de/service/kuechen-service-von-reddy/
ul:de
de:UTF-8
dt:Küchen-Service von REDDY: Immer für Sie da
sd:24-bit
sr:1920x1200
vp:1413x1094
je:0
ec:Videos
ea:Pause
el:REDDY Küchen
_u:yDCAAEAjY~
jid:
gjid:
cid:1916252056.1502875620
tid:UA-46324974-1
_gid:525342343.1506496235
gtm:GTM-KNPBCS
z:1669774651

v:1
_v:j63
a:1663437289
t:event
ni:0
_s:1
dl:https://www.reddy.de/service/kuechen-service-von-reddy/
ul:de
de:UTF-8
dt:Küchen-Service von REDDY: Immer für Sie da
sd:24-bit
sr:1920x1200
vp:1413x1094
je:0
ec:Videos
ea:Pause
el:REDDY Küchen
_u:yDCAAEAjY~
jid:
gjid:
cid:1916252056.1502875620
tid:UA-46324974-1
_gid:525342343.1506496235
gtm:GTM-KNPBCS
z:1115972435

They are identical except for the z parameter.

Thanks.

**Comment by DanWilkerson** [comment]
This is a Vimeo player.js issue - there's an older version included in the vhs-assets-...-.js file that has this bug:

https://github.com/vimeo/player.js/issues/108

I used Charles Proxy to replace the version in the vhs-assets file (2.0.2) with the latest version and it fixed the issue.

**Comment by KeerthiAR** [comment]
Hello, 
I'm using vimeo tracking tag and it is working fine (firing an event at 10,25,50,75,90,play, pause and Watch to end triggers) for the first time.
without loading the page if we view the same video again, then it is firing at play, pause and watch to end triggers only. So im not able to track 10, 25,50, 75 & 90. Because of this the count in analytics is becoming wrong. Watch to end count is more than 90% which looks wierd... can some one please suggest me how to proceed...
